<?php
    echo "<div class=\"section-colored text-center\">\n";
    echo "    <div class=\"container\">\n";
    echo "        <div class=\"row\">\n";
    echo "            <div class=\"col-lg-12\">\n";
    echo "                <h1>Web Service Radio Application</h1>\n";
    echo "                <h3>A Great Way to Relax and Enjoy your Studies!</h3>\n";
    echo "                <p>A project created for use in CS 425: Server Side Web Development taught by Dr. Binto George.</p>\n";
    echo "                <hr>\n";
    echo "            </div>\n";
    echo "        </div>\n";
    echo "    </div>\n";
    echo "</div>\n";
    echo "\n";
    echo "<div class=\"section-colored\">\n";
    echo "\n";
    echo "    <div class=\"container\">\n";
    echo "        <div class=\"row\">\n";
    echo "            <div class=\"col-lg-6 col-md-6 col-sm-6\">\n";
    echo "                <h2>Some Features Include:</h2>\n";
    echo "                <ul>\n";
    echo "                    <li>Pause, Play, Forward, Previous</li>\n";
    echo "                    <li>Artist Name, Song Name, and our SVG Logo!</li>\n";
    echo "                    <li>3 Song Library!</li>\n";
    echo "                </ul>\n";
    echo "            </div>\n";
    echo "            <div class=\"col-lg-6 col-md-6 col-sm-6\">\n";
    echo "                <img src=\"svg/newlogo.svg\" class=\"center\">\n";
    echo "\n";
    echo "                <audio controls>\n";
    echo "                    <source src=\"https://www.coothead.co.uk/audio/You-Cant-Always-Get-What-You-Want.mp3\" type=\"audio/mpeg\">\n";
    echo "                </audio>\n";
    echo "            </div>\n";
    echo "        </div>\n";
    echo "    </div>\n";
    echo "</div>\n";
    echo "\n";
    echo "<br>\n";
    echo "\n";
    echo "<div class=\"container\">\n";
    echo "    <div class=\"row well\">\n";
    echo "        <div class=\"col-lg-8 col-md-8\">\n";
    echo "            <h4>Through our education achieved at Western Illinois University this was possible.</h4>\n";
    echo "            <p>Check out our school's website through the button to the right!</p>\n";
    echo "        </div>\n";
    echo "        <div class=\"col-lg-4 col-md-4\">\n";
    echo "            <a class=\"btn btn-purple btn-primary pull-right\" href=\"https://www.wiu.edu/\">Western Illinois University</a>\n";
    echo "        </div>\n";
    echo "    </div>\n";
    echo "</div>\n";
?>
